/* SPDX-License-Identifier: GPL-3.0-only */
/*
    ZEsarPCW -- Amstrad PCW libretro core (derived from ZEsarUX).
    Copyright (c) 2026 retrodiv <retrodiv@proton.me>. Distributed under the GNU General Public License v3
    (the same licence as ZEsarUX, Copyright (C) Cesar Hernandez Bano).

    ZEsarPCW -- Amstrad PCW libretro core (derived from ZEsarUX) -- on-screen keyboard (renderer + injector)

    ============================================================================
    WHAT THIS IS
    ============================================================================
    A PCW keyboard drawn over the running game and navigated with the gamepad, so
    the catalogue's text adventures and CP/M programs (which need a real keyboard)
    are playable with a pad. libretro.c opens/closes it on SELECT (or L3), routes
    the pad to pcw_osk_handle_input() while it is up, ticks pcw_osk_tick() every
    frame (for auto-release), and calls pcw_osk_render() after composing the game
    frame. Self-contained: it owns its layout and draws into the core's XRGB8888
    framebuffer -- no frontend overlay involved.

    ============================================================================
    THE SKINS  (pcw_osk_skin_{uk,us}.h, GENERATED by gen_osk_skin.py)
    ============================================================================
    The look comes from the pixel-art PCW8256 locale PNGs
    (mappings/Keyboard_UK.png and Keyboard_US.png), decomposed by the generator
    into: a stretchable bevel "empty-button" template
    (4 colours + a rule), 1bpp legend sprites, baked RGBA sprites for irregular
    keys (the tall stepped RETURN), and a skin_keys[] table (geometry + PCW matrix
    cell + kind + flags) -- see that script's header for the full story and the PNG
    format. THIS FILE must keep `tmpl_pixel()` identical to the generator's
    `template_pixel()` (the bevel rule lives in BOTH; change both together).

    ============================================================================
    RENDERING
    ============================================================================
    build_panel() composes the whole PNG (AMSTRAD header + divider + keys) into a
    360x133 ARGB cache ONCE (template chrome or baked sprite + legend per key).
    Each frame pcw_osk_render() scale-blits that cache, then overlays the DYNAMIC
    things the cache can't hold: a SOLID amber fill on any armed sticky modifier
    (both SHIFT keys / ALT / EXTRA / LOCK -- so you can see one is latched while you
    move to the next key), the amber selection TINT on the current key, and the
    SHIFT-LOCK 2x2 indicator (granate off / red on).

    Scaling is the user's decision (see gen_osk_skin.py): on the 720-wide MONO
    screen only the WIDTH is doubled (g_scale_x=2, g_scale_y=1) -- a mono pixel is
    half as wide as a 360-mode pixel, so doubling width alone preserves the
    keyboard's real-world proportions. The whole panel (header included) is shown,
    bottom-anchored; at native height (133) it fits in the 256-line frame and
    leaves the game visible above. opt_transparent (menu labels in parentheses):
    0 "Solid - Full" (whole panel); 2 "Solid - Only keys" (KEYS ONLY, solid); 1
    "Transparent" (KEYS ONLY, blended over the game). Modes 1 and 2 drop the
    background, AMSTRAD logo and divider -- the game shows between the keys; mode 1
    is just the see-through version of mode 2.

    ============================================================================
    INJECTION  (into the PCW key matrix, machines/pcw.c)
    ============================================================================
    Each key carries its PCW matrix cell (row + mask) OR a util_teclas code (the
    cursor cluster). The matrix is ACTIVE-LOW: press = clear the bit, release =
    set it (press_one). A tapped key (+ any one-shot modifiers) is remembered in
    pending[] and auto-released after opt_release_frames (pcw_osk_tick). That
    duration is a minimum for short taps: holding the physical A/X/Y button keeps
    the emulated PCW key down until the physical button is released.
    Modifiers SHIFT/ALT/EXTRA are STICKY one-shots (latch for the next key);
    SHIFT-LOCK is a persistent SHIFT held down until toggled off. NEEDS_SHIFT keys
    (the odd f1/f3/f5/f7 = SHIFT+even, and shifted symbols) press SHIFT alongside,
    unless LOCK already holds it.

    ============================================================================
    NAVIGATION
    ============================================================================
    build_nav() groups skin_keys[] into NNAV rows (by navrow), sorted by x. The
    d-pad moves within/between rows (up/down snap to the nearest key by x-centre);
    L/R jump along a row; A taps; B closes; Y/X are quick DEL / RETURN taps.

    Distributed under the GNU General Public License v3 (same as ZEsarUX).
*/

#include <string.h>

#include "pcw_osk.h"
#include "pcw_keyboard.h"
#include "pcw.h"              /* z80_byte + the PCW keyboard matrix               */
#include "pcw_osk_skin_uk.h"  /* generated locale skins (keys + sprites)         */
#include "pcw_osk_skin_us.h"
#include "libretro.h"         /* RETRO_DEVICE_ID_JOYPAD_*                          */

/* ------------------------------------------------------------------------- *
 * state
 * ------------------------------------------------------------------------- */
static int  active = 0;
static int  opt_release_frames = 3;      /* 60 ms at 50 fps */
static int  opt_transparent = 0;
static const pcw_osk_skin_t *g_skin = &pcw_osk_skin_uk; /* core-option default */

/* sticky modifiers */
static int  mod_shift = 0, mod_alt = 0, mod_extra = 0, mod_lock = 0;

/* a key (or modifier) we can press/release: a PCW matrix cell, or a util code */
typedef struct { uint8_t prow, pmask; int16_t util; } press_t;

static const press_t P_SHIFT = { 2, 0x20, 0 };   /* matrix shift */
static const press_t P_ALT   = { 0xA, 0x80, 0 };
static const press_t P_EXTRA = { 0xA, 0x02, 0 };

/* auto-release of a tapped key (+ its one-shot modifiers) */
static press_t pending[6];
static int     pending_n = 0;
static int     pending_frames = 0;
static int     pending_hold_id = -1;   /* physical RetroPad button extending the hold */

/* edge state for the nav buttons, indexed by RetroPad id */
static int prev[20];
static int (*g_poll)(int);

/* ------------------------------------------------------------------------- *
 * navigation grid: skin keys grouped by navrow, sorted by x
 * ------------------------------------------------------------------------- */
#define NNAV 5
static int  navlist[NNAV][40];
static int  navcount[NNAV];
static int  nav_built = 0;
static int  sel_row = 2, sel_pos = 1;    /* start on 'A' (caps row) */

static void build_nav(void)
{
    int r, i;
    if (nav_built) return;
    for (r = 0; r < NNAV; r++) navcount[r] = 0;
    for (i = 0; i < g_skin->nkeys; i++) {
        int row = g_skin->keys[i].navrow, n, p;
        int *lst;
        if (row < 0 || row >= NNAV) continue;
        lst = navlist[row]; n = navcount[row];
        if (n >= 40) continue;
        for (p = n; p > 0 && g_skin->keys[lst[p-1]].x > g_skin->keys[i].x; p--)
            lst[p] = lst[p-1];
        lst[p] = i;
        navcount[row]++;
    }
    if (sel_pos >= navcount[sel_row]) sel_pos = navcount[sel_row] - 1;
    if (sel_pos < 0) sel_pos = 0;
    nav_built = 1;
}

static int sel_index(void) { return navlist[sel_row][sel_pos]; }
static int key_cx(int i)   { return g_skin->keys[i].x + g_skin->keys[i].w / 2; }

static void move_h(int dir)
{
    sel_pos += dir;
    if (sel_pos < 0) sel_pos = navcount[sel_row] - 1;
    if (sel_pos >= navcount[sel_row]) sel_pos = 0;
}

static void move_v(int dir)
{
    int cx = key_cx(sel_index());
    int best = 0, bestd = 1 << 30, p;
    sel_row = (sel_row + dir + NNAV) % NNAV;
    for (p = 0; p < navcount[sel_row]; p++) {
        int d = key_cx(navlist[sel_row][p]) - cx; if (d < 0) d = -d;
        if (d < bestd) { bestd = d; best = p; }
    }
    sel_pos = best;
}

/* ------------------------------------------------------------------------- *
 * injection (direct PCW matrix; pressed = clear bit, released = set bit)
 * ------------------------------------------------------------------------- */
static void press_one(press_t p, int down)
{
    if (p.util)        pcw_keyboard_set_util_key(p.util, down != 0);
    else if (p.pmask) {
        if (down) pcw_keyboard_table[p.prow] &= (z80_byte)~p.pmask;
        else      pcw_keyboard_table[p.prow] |=  p.pmask;
    }
}

static void flush_pending(void)
{
    int i;
    for (i = 0; i < pending_n; i++) press_one(pending[i], 0);
    pending_n = 0;
    pending_frames = 0;
    pending_hold_id = -1;
}

void pcw_osk_set_options(int release_ms, int transparent, int layout_us)
{
    const pcw_osk_skin_t *wanted = layout_us ? &pcw_osk_skin_us : &pcw_osk_skin_uk;
    if (release_ms < 60) release_ms = 60;
    opt_release_frames = release_ms / 20;          /* 50 fps -> 20 ms/frame */
    if (opt_release_frames < 1) opt_release_frames = 1;
    opt_transparent = (transparent < 0) ? 0 : (transparent > 2) ? 2 : transparent;  /* 0 solid, 1 transp, 2 semi */
    if (g_skin != wanted) {
        g_skin = wanted;
        nav_built = 0;
    }
}

int  pcw_osk_is_active(void) { return active; }

void pcw_osk_close(void)
{
    flush_pending();
    if (mod_lock) { press_one(P_SHIFT, 0); mod_lock = 0; }
    mod_shift = mod_alt = mod_extra = 0;
    active = 0;
}

void pcw_osk_reset(void)
{
    pcw_osk_close();
    memset(prev, 0, sizeof prev);
    g_poll = NULL;
    sel_row = 2;
    sel_pos = 1;
}

void pcw_osk_toggle(void)
{
    if (active) pcw_osk_close();
    else { active = 1; build_nav(); memset(prev, 0, sizeof prev); }
}

/* ------------------------------------------------------------------------- *
 * key activation
 * ------------------------------------------------------------------------- */
static void press_selected(int hold_id)
{
    const pcw_osk_skin_key_t *k = &g_skin->keys[sel_index()];

    switch (k->kind) {
        case SK_SHIFT: mod_shift ^= 1; return;
        case SK_ALT:   mod_alt   ^= 1; return;
        case SK_EXTRA: mod_extra ^= 1; return;
        case SK_LOCK:
            mod_lock ^= 1;
            press_one(P_SHIFT, mod_lock ? 1 : 0);   /* LOCK is a persistent SHIFT */
            return;
        default: break;
    }
    if (!k->pmask && !k->util) return;   /* drawn but not wired */

    flush_pending();   /* let go of any still-held tap first */
    pending_n = 0;

    /* SHIFT for the shifted-symbol / odd-f keys, unless LOCK already holds it */
    if (((k->flags & SKF_NEEDS_SHIFT) || mod_shift) && !mod_lock) {
        press_one(P_SHIFT, 1); pending[pending_n++] = P_SHIFT;
    }
    if (mod_extra) { press_one(P_EXTRA, 1); pending[pending_n++] = P_EXTRA; }
    if (mod_alt)   { press_one(P_ALT,   1); pending[pending_n++] = P_ALT; }

    {
        press_t pk; pk.prow = k->prow; pk.pmask = k->pmask; pk.util = k->util;
        press_one(pk, 1); pending[pending_n++] = pk;
    }
    pending_frames = opt_release_frames;
    pending_hold_id = hold_id;
    mod_shift = mod_alt = mod_extra = 0;   /* one-shot modifiers consumed */
}

static void quick_tap(uint8_t row, uint8_t mask, int hold_id)
{
    press_t p; p.prow = row; p.pmask = mask; p.util = 0;
    flush_pending();
    press_one(p, 1);
    pending[0] = p; pending_n = 1; pending_frames = opt_release_frames;
    pending_hold_id = hold_id;
}

/* ------------------------------------------------------------------------- *
 * input
 * ------------------------------------------------------------------------- */
static int edge(int id)
{
    int now = g_poll(id) ? 1 : 0;
    int e = now && !prev[id];
    prev[id] = now;
    return e;
}

void pcw_osk_handle_input(int (*poll)(int id))
{
    if (!active) return;
    g_poll = poll;

    if (edge(RETRO_DEVICE_ID_JOYPAD_UP))    move_v(-1);
    if (edge(RETRO_DEVICE_ID_JOYPAD_DOWN))  move_v(+1);
    if (edge(RETRO_DEVICE_ID_JOYPAD_LEFT))  move_h(-1);
    if (edge(RETRO_DEVICE_ID_JOYPAD_RIGHT)) move_h(+1);

    if (edge(RETRO_DEVICE_ID_JOYPAD_L)) { sel_pos -= 3; if (sel_pos < 0) sel_pos = 0; }
    if (edge(RETRO_DEVICE_ID_JOYPAD_R)) { sel_pos += 3; if (sel_pos >= navcount[sel_row]) sel_pos = navcount[sel_row] - 1; }

    if (edge(RETRO_DEVICE_ID_JOYPAD_A)) press_selected(RETRO_DEVICE_ID_JOYPAD_A);

    /* convenience taps that do not move the selection */
    if (edge(RETRO_DEVICE_ID_JOYPAD_Y))
        quick_tap(9, 0x80, RETRO_DEVICE_ID_JOYPAD_Y);   /* del<  (backspace) */
    if (edge(RETRO_DEVICE_ID_JOYPAD_X))
        quick_tap(2, 0x04, RETRO_DEVICE_ID_JOYPAD_X);   /* return            */
}

void pcw_osk_tick(void)
{
    if (pending_frames > 0) {
        /* Count down the configured minimum tap duration, but stop at one frame
           while the activating physical button remains held. On release the
           final tick lets go immediately if that minimum has already elapsed. */
        int held = g_poll && pending_hold_id >= 0 && g_poll(pending_hold_id);
        if (pending_frames > 1 || !held) {
            if (--pending_frames == 0) flush_pending();
        }
    }
}

/* ------------------------------------------------------------------------- *
 * rendering -- compose the skin once, then scale-blit + dynamic overlays
 * ------------------------------------------------------------------------- */
#define OSK_PANEL_MAX_W ((PCW_OSK_SKIN_UK_W > PCW_OSK_SKIN_US_W) ? PCW_OSK_SKIN_UK_W : PCW_OSK_SKIN_US_W)
#define OSK_PANEL_MAX_H ((PCW_OSK_SKIN_UK_H > PCW_OSK_SKIN_US_H) ? PCW_OSK_SKIN_UK_H : PCW_OSK_SKIN_US_H)
static uint32_t panel[OSK_PANEL_MAX_W * OSK_PANEL_MAX_H];
static const pcw_osk_skin_t *panel_skin = NULL;

static uint32_t tmpl_pixel(int lx, int ly, int w, int h)
{
    if (ly == 0 || ly == h - 1) return g_skin->c_outer;     /* outer top/bottom */
    if (lx == 0 || lx == w - 1) return g_skin->c_outer;     /* outer left/right */
    if (ly == 1 || lx == 1 || lx == w - 2) return g_skin->c_inner;  /* inner L/T/R */
    return g_skin->c_face;
}

static void build_panel(void)
{
    int i, x, y;
    if (panel_skin == g_skin) return;

    for (i = 0; i < g_skin->width * g_skin->height; i++) panel[i] = g_skin->c_bg;
    for (y = 0; y < g_skin->header_height; y++)
        for (x = 0; x < g_skin->width; x++)
            panel[y * g_skin->width + x] = g_skin->header[y * g_skin->width + x];

    for (i = 0; i < g_skin->nkeys; i++) {
        const pcw_osk_skin_key_t *k = &g_skin->keys[i];
        int lx, ly;
        if (k->flags & SKF_BAKED) {
            const pcw_osk_skin_baked_t *b = &g_skin->bakeds[k->baked];
            for (ly = 0; ly < b->h; ly++)
                for (lx = 0; lx < b->w; lx++) {
                    uint32_t c = g_skin->baked_pix[b->off + ly * b->w + lx];
                    int X = k->x + lx, Y = k->y + ly;
                    if (c && X >= 0 && X < g_skin->width && Y >= 0 && Y < g_skin->height)
                        panel[Y * g_skin->width + X] = c;
                }
        } else {
            for (ly = 0; ly < k->h; ly++)
                for (lx = 0; lx < k->w; lx++) {
                    int X = k->x + lx, Y = k->y + ly;
                    if (X >= 0 && X < g_skin->width && Y >= 0 && Y < g_skin->height)
                        panel[Y * g_skin->width + X] = tmpl_pixel(lx, ly, k->w, k->h);
                }
        }
        if (k->label >= 0) {
            const pcw_osk_skin_label_t *l = &g_skin->labels[k->label];
            int stride = (l->w + 7) / 8;
            int ox = k->x + k->lx, oy = k->y + k->ly;   /* artist-exact legend position */
            for (ly = 0; ly < l->h; ly++)
                for (lx = 0; lx < l->w; lx++)
                    if (g_skin->label_bits[l->off + ly * stride + (lx >> 3)] & (0x80 >> (lx & 7))) {
                        int X = ox + lx, Y = oy + ly;
                        if (X >= 0 && X < g_skin->width && Y >= 0 && Y < g_skin->height)
                            panel[Y * g_skin->width + X] = g_skin->c_text;
                    }
        }
    }
    panel_skin = g_skin;
}

static uint32_t blend(uint32_t a, uint32_t b, int num, int den)  /* a*num + b*(den-num) */
{
    int ra=(a>>16)&0xff, ga=(a>>8)&0xff, ba=a&0xff;
    int rb=(b>>16)&0xff, gb=(b>>8)&0xff, bb=b&0xff;
    int r=(ra*num + rb*(den-num))/den;
    int g=(ga*num + gb*(den-num))/den;
    int bl=(ba*num + bb*(den-num))/den;
    return 0xFF000000u | (r<<16) | (g<<8) | bl;
}

/* geometry of the current blit, set by pcw_osk_render */
static int g_scale_x, g_scale_y, g_ox, g_oy, g_w, g_h, g_stride;
static uint32_t *g_fb;

/* Map one panel pixel (sx, sy) -> a scale_x by scale_y block in the framebuffer.
   On the 720-wide mono screen only the WIDTH is doubled (scale_x=2, scale_y=1):
   a mono pixel is half as wide as a 360-mode pixel, so this keeps the keyboard
   the same physical proportions as in the colour modes -- and at native height
   the whole PNG (AMSTRAD header, divider line and all) still fits, bottom-anchored. */
static void put_block(int sx, int sy, uint32_t c)
{
    int xx, yy;
    for (yy = 0; yy < g_scale_y; yy++) {
        int Y = g_oy + sy * g_scale_y + yy;
        if (Y < 0 || Y >= g_h) continue;
        for (xx = 0; xx < g_scale_x; xx++) {
            int X = g_ox + sx * g_scale_x + xx;
            if (X < 0 || X >= g_w) continue;
            g_fb[Y * g_stride + X] = c;
        }
    }
}

/* True only for pixels belonging to this key. Rectangular template keys own
   their whole bounds. A baked irregular key (the stepped RET) owns only its
   non-transparent sprite pixels: its bounding box overlaps the neighbouring
   key. The skin generator excludes that neighbour from the sprite, so focus
   preserves RET's upper-left extension without tinting the adjacent key. */
static int key_owns_pixel(const pcw_osk_skin_key_t *k, int sx, int sy)
{
    int lx = sx - k->x, ly = sy - k->y;
    if (lx < 0 || ly < 0 || lx >= k->w || ly >= k->h) return 0;
    if (k->flags & SKF_BAKED) {
        const pcw_osk_skin_baked_t *b = &g_skin->bakeds[k->baked];
        if (lx >= b->w || ly >= b->h) return 0;
        return g_skin->baked_pix[b->off + ly * b->w + lx] != 0;
    }
    return 1;
}

void pcw_osk_render(uint32_t *fb, int width, int height, int stride)
{
    int sx, sy, i;
    const uint32_t SEL = 0xFFF2B43A;   /* amber selection tint */

    if (!active) return;
    build_nav();
    build_panel();

    g_fb = fb; g_w = width; g_h = height; g_stride = stride;
    g_scale_x = (2 * g_skin->width <= width) ? 2 : 1;  /* double width on 720 mono */
    g_scale_y = 1;                                     /* never double the height  */
    g_ox = (width  - g_skin->width * g_scale_x) / 2;   /* horizontally centred     */
    g_oy = height - g_skin->height * g_scale_y;        /* whole PNG, bottom-anchored */

    /* base panel. opt_transparent (menu label):
         0 "Solid - Full"      -- the whole PNG (AMSTRAD header + divider + keys), opaque.
         1 "Transparent"       -- KEYS ONLY, blended over the game (the see-through
                                  version of "Solid - Only keys": no bg / logo / divider).
         2 "Solid - Only keys" -- KEYS ONLY, solid: no background, no AMSTRAD logo and
                                  no divider; the game shows through except the keys. */
    {
        int keys_only = (opt_transparent != 0);          /* modes 1 and 2 drop bg + header */
        int top = keys_only ? g_skin->header_height : 0;
        for (sy = top; sy < g_skin->height; sy++)
            for (sx = 0; sx < g_skin->width; sx++) {
                uint32_t c = panel[sy * g_skin->width + sx];
                if (keys_only && c == g_skin->c_bg) continue; /* drop background, keep keys */
                if (opt_transparent == 1) {                  /* Transparent: blend the keys */
                    int X = g_ox + sx * g_scale_x, Y = g_oy + sy * g_scale_y;
                    uint32_t under = (X >= 0 && X < width && Y >= 0 && Y < height)
                                   ? (fb[Y * stride + X] | 0xFF000000u) : 0xFF000000u;
                    put_block(sx, sy, blend(c, under, 7, 16));
                } else {                                     /* Solid panel / Only keys: opaque */
                    put_block(sx, sy, c | 0xFF000000u);
                }
            }
    }

    /* latched sticky modifiers: keep their key(s) lit in SOLID amber so an armed
       modifier is obvious while you move to the next key. SHIFT/ALT/EXTRA latch for
       the next keypress (one-shot); LOCK stays until toggled. Both SHIFT keys light
       together. The legend pixels are left untouched so the label stays readable. */
    for (i = 0; i < g_skin->nkeys; i++) {
        const pcw_osk_skin_key_t *k = &g_skin->keys[i];
        int on = (k->kind == SK_SHIFT && mod_shift) || (k->kind == SK_ALT && mod_alt) ||
                 (k->kind == SK_EXTRA && mod_extra) || (k->kind == SK_LOCK && mod_lock);
        if (!on) continue;
        for (sy = k->y; sy < k->y + k->h && sy < g_skin->height; sy++)
            for (sx = k->x; sx < k->x + k->w && sx < g_skin->width; sx++) {
                uint32_t base = panel[sy * g_skin->width + sx];
                if (base == g_skin->c_bg || base == g_skin->c_text) continue; /* gaps + legend */
                put_block(sx, sy, SEL);                                  /* solid amber = armed */
            }
    }

    /* selection: tint the selected key's face amber (keeps the legend on top) */
    {
        const pcw_osk_skin_key_t *k = &g_skin->keys[sel_index()];
        for (sy = k->y; sy < k->y + k->h && sy < g_skin->height; sy++)
            for (sx = k->x; sx < k->x + k->w && sx < g_skin->width; sx++) {
                uint32_t base = panel[sy * g_skin->width + sx];
                if (!key_owns_pixel(k, sx, sy) || base == g_skin->c_bg) continue;
                put_block(sx, sy, blend(SEL, base, 8, 16));
            }
    }

    /* SHIFT-LOCK indicator: 2x2, granate off / red on */
    for (i = 0; i < g_skin->nkeys; i++) {
        const pcw_osk_skin_key_t *k = &g_skin->keys[i];
        uint32_t dc;
        int dx, dy;
        if (!(k->flags & SKF_LOCKDOT) || k->dotx < 0) continue;
        dc = mod_lock ? g_skin->c_lockon : g_skin->c_lockoff;
        for (dy = 0; dy < 2; dy++)
            for (dx = 0; dx < 2; dx++)
                put_block(k->dotx + dx, k->doty + dy, dc);
    }
}
